"""Create IPO table

Revision ID: e94be6cdf59d
Revises: 
Create Date: 2025-03-04 22:33:49.333135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e94be6cdf59d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipo_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('issue_size', sa.Numeric(), nullable=True),
    sa.Column('price_band', sa.String(), nullable=True),
    sa.Column('issue_type', sa.String(), nullable=True),
    sa.Column('ipo_type', sa.String(), nullable=True),
    sa.Column('fresh_issue', sa.String(), nullable=True),
    sa.Column('offer_for_sale', sa.String(), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('ipo_open_date', sa.Date(), nullable=True),
    sa.Column('ipo_close_date', sa.Date(), nullable=True),
    sa.Column('rhp_file_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipo_details_id'), 'ipo_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ipo_details_id'), table_name='ipo_details')
    op.drop_table('ipo_details')
    # ### end Alembic commands ###
